### ISSUE TITLE
Update local FaceNet database on Nano

### ISSUE THREAD

**Issue by ryspark** [orangese/facial-recognition#21]
Photo link: https://halbrown.photoreflect.com/store/Photos.aspx?e=10785352 (see Discord for password).

Need to crawl this website and download all available photos, then run the facial detection/recognition script on those downloaded photos. The facial recognition part is already written, so all that's left to do is download the photos and name them properly (ex: `john_smith_1.jpg`).

**Comment by abarker0** [comment]
pr 24: initial, incomplete, untested version of webscrape.py

**Comment by ryspark** [comment]
## WEEK 3 UPDATE

Chris, Alex: try Google authentification to get around token/cookie issue?
* Login allows you to view the image once
* Manual cookie saving?

**Comment by ryspark** [comment]
## WEEK 5

### Update
* Webscraping isn't working - cookie issue (or more)

### Goals
* Contact Dhruv, see if he has any relevant code
* Explore manual options (Screenshot images manually?)
* Screenshot programmatically throughout image links

**Comment by ryspark** [comment]
## WEEK 6

### Update
* Screenshot working?
* Dhruv had Chrome extension

### Goals
* Alex: Try Dhruv's method
* Chris: programmatic screenshots
* Kevin: script to crop screenshots

**Comment by ryspark** [comment]
Closed by #33
